<a href="https://colab.research.google.com/github/claudelepere/ML_GitHub/blob/main/BERT_for_multi_label_text_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## IMPORTANT

Process any ipynb file only with the editor in which it was created, don't open a JupyterLab ipynb with Colab and vice versa, don't open any ipynb with an editor that can render the display of a notebook, like VS Code or VSCodium.

Why? Because any ipynb contains metadata specific to each notebook editor and another editor may modify them.

---

Do not use conda in Colab notebook, do not try to install with conda, use pip.

---

Do not launch wandb (cannot connect to the W&B server): 3 things: #!pip install, #import, os.environ disable

In [ ]:
!pip install -q accelerate
!pip install -q huggingface_hub
!pip install -q scikit-learn
!pip install -q transformers datasets
!pip install -q wandb

import json
import numpy as np
import os
import sys
import time
import torch
import wandb

from datasets              import DatasetDict
from google.colab          import auth, drive, files, userdata
from huggingface_hub       import create_repo, login, upload_file
from huggingface_hub.utils import RepositoryNotFoundError
from sklearn.metrics       import accuracy_score, average_precision_score, classification_report, f1_score, precision_score, recall_score, roc_auc_score
from torch.utils.data      import DataLoader
from tqdm.auto             import tqdm
from transformers          import AutoModelForSequenceClassification, AutoTokenizer, EvalPrediction, Trainer, TrainingArguments

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 12.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 8.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 11.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 9.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 12.3 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.9.0 which is incompatible.


In [ ]:
"""
# Check the Python version
print(sys.version)
print()

# Get the installed packages (you can see that conda is not installed (do not install it))
!pip list
print()

# Check system information
!cat /etc/os-release
!uname -m
print()

# Check the GPU details (only if the runtime type is T4 GPU)
#!nvidia-smi
#print()

# Check RAM
!free -h
print()

# Check disk space
!df -h
print()

# Get environment variables
for key, value in os.environ.items():
    print(f"{key}: {value}")
"""

print(f"currentdir: {os.getcwd()}")
print()

# Check the device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"device: {device}")

currentdir: /content

device: cuda


In [ ]:
# Google Colab authenticate

# Required for accessing Colab Secrets: not necessary for Hugging Face Hub, for wandb, you still have to enter manually
#auth.authenticate_user()

In [ ]:
# Hugging Face authenticate

os.environ["HF_TOKEN"] = userdata.get("HF_TOKEN")    # Store the key in os.environ
hf_token               = os.environ.get('HF_TOKEN')
login(token=hf_token)

# Verify
!huggingface-cli whoami

Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.


claudelepere


In [ ]:
# Create the skill_classification repo on the Hugging Face Hub

HF_name         = "claudelepere/skill_classification"
repo_id_model   = HF_name
repo_id_dataset = HF_name

repo_model_url = create_repo(
    repo_id   = repo_id_model,
    repo_type = "model",
    private   = True,
    exist_ok  = True
    )
print(f"Repo model url: {repo_model_url} created successfully as a private repo.")

repo_dataset_url = create_repo(
    repo_id   = repo_id_dataset,
    repo_type = "dataset",
    private   = True,
    exist_ok  = True
    )
print(f"Repo datasets url: {repo_dataset_url} created successfully as a private repo.")

repo_id_dataset = f"datasets/{HF_name}"

print(f"repo_id_model: {repo_id_model}")
print(f"repo_id_dataset: {repo_id_dataset}")

Repo model url: https://huggingface.co/claudelepere/skill_classification created successfully as a private repo.
Repo datasets url: https://huggingface.co/datasets/claudelepere/skill_classification created successfully as a private repo.
repo_id_model: claudelepere/skill_classification
repo_id_dataset: datasets/claudelepere/skill_classification


In [ ]:
# Weights & Biases (W&B, wandb) authenticate

#os.environ["WANDB_DISABLE_CODE"] = "true"
os.environ["WANDB_API_KEY"] = userdata.get("WANDB_API_KEY")        # Store the key in os.environ
wandb_api_key               = os.environ.get('WANDB_API_KEY')

wandb.login(relogin=True)                                          # Force relogin

try:
  wandb.init(
      project="skill_classification",
      #entity="claudelepere",
      entity = "claudelepere-c-cile-cy"
      )
except wandb.errors.CommError as e:
  print(f"CommError: {e}")
except Exception as e:
  print(f"Exception: {e}")

wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.


<IPython.core.display.Javascript object>

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit:

 ··········


wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: claudelepere (claudelepere-c-cile-cy). Use `wandb login --relogin` to force relogin


# My fine-tuning BERT (and friends) for multi-label text classification

In this notebook, we are going to fine-tune BERT to predict one or more labels for a given piece of text. Note that this notebook illustrates how to fine-tune a bert-base-uncased model, but you can also fine-tune a RoBERTa, DeBERTa, DistilBERT, CANINE, ... checkpoint in the same way.

All of those work in the same way: they add a **linear layer on top of the base model, which is used to produce a tensor of shape (batch_size, num_labels)**, indicating the unnormalized scores for a number of labels for every example in the batch.



## Set-up environment

First, we install the libraries which we'll use: HuggingFace Transformers and Datasets.

## Load dataset

Next, let's download a multi-label text classification dataset from the [hub](https://huggingface.co/).

At the time of writing, I picked a random one as follows:   

* first, go to the "datasets" tab on huggingface.co
* next, select the "multi-label-classification" tag on the left as well as the the "1k<10k" tag (fo find a relatively small dataset).

Note that you can also easily load your local data (i.e. csv files, txt files, Parquet files, JSON, ...) as explained [here](https://huggingface.co/docs/datasets/loading.html#local-and-remote-files).



In [ ]:
# Upload and unzip the dataset zip file

uploaded_files     = files.upload()
uploaded_file_name = list(uploaded_files.keys())[0]
print(f"uploaded_file_name: {uploaded_file_name} {len(uploaded_files)}")

!unzip {uploaded_file_name}

unzipped_file_dir_name = os.path.splitext(uploaded_file_name)[0]
print(f"unzipped_file_dir_name: {unzipped_file_dir_name}")

Saving dataset_11_1000.zip to dataset_11_1000.zip
uploaded_file_name: dataset_11_1000.zip 1
Archive:  dataset_11_1000.zip
  inflating: dataset_11_1000/dataset_dict.json  
  inflating: dataset_11_1000/test/data-00000-of-00001.arrow  
  inflating: dataset_11_1000/test/dataset_info.json  
  inflating: dataset_11_1000/test/state.json  
  inflating: dataset_11_1000/train/data-00000-of-00001.arrow  
  inflating: dataset_11_1000/train/dataset_info.json  
  inflating: dataset_11_1000/train/state.json  
  inflating: dataset_11_1000/validation/data-00000-of-00001.arrow  
  inflating: dataset_11_1000/validation/dataset_info.json  
  inflating: dataset_11_1000/validation/state.json  
unzipped_file_dir_name: dataset_11_1000


In [ ]:
# Create the dataset: 3 Hugging Face Dataset in a Hugging Face DatasetDict

dataset = DatasetDict.load_from_disk(unzipped_file_dir_name)

print(f"dataset: {type(dataset)} {dataset.shape}\n{dataset}")

dataset: <class 'datasets.dataset_dict.DatasetDict'> {'train': (800, 8), 'validation': (50, 8), 'test': (150, 8)}
DatasetDict({
    train: Dataset({
        features: ['id', 'text', '390', '135', '136', '137', '138', '139'],
        num_rows: 800
    })
    validation: Dataset({
        features: ['id', 'text', '390', '135', '136', '137', '138', '139'],
        num_rows: 50
    })
    test: Dataset({
        features: ['id', 'text', '390', '135', '136', '137', '138', '139'],
        num_rows: 150
    })
})


As we can see, the dataset contains 3 splits: one for training, one for validation and one for testing.

Let's test the first example of the training split:

In [ ]:
example = dataset['train'][0]
print(f"example: {type(example)} {example.keys()}\n{example}")

example: <class 'dict'> dict_keys(['id', 'text', '390', '135', '136', '137', '138', '139'])
{'id': 305473, 'text': 'Talencia Consulting - Service Delivery Coordinator Power BI, Jira, MS 365 Talencia Consulting Talencia Consulting is currently looking for a Service Delivery Coordinator for one of our renowned clients based in Brussels. Start date: 01/07/24 Duration: Mid to long term assignment Homeworking: Hybrid Mission Monitor and report performance of support partners and propose improvements and solutions to incidents Run govenance and reporting meetings Manage daily escalation with vendors Carry out financial tasks in systems Requirements Bachelor or Masters degree or equivalent by experience At least 1 year of experience in a similar position (service delivery) Knowledge of working with IT Support partners/processes Knowledge of MS 365 applications, Power BI and Jira Fluent in English', '390': False, '135': False, '136': True, '137': True, '138': True, '139': False}


In [ ]:
# Create the label list and the id2label and label2id mappings.

"""
labels
    if dataset 7_1000_125_125  , 48 labels
    if dataset 7_128_18_54     , 42 labels
    if dataset 8910_1087_68_204, 206 labels
"""

labels = [label for label in dataset['train'].features.keys() if label not in ['id', 'text']]
labels.sort()
print(f"labels: {type(labels)} {len(labels)}\n{labels}")

id2label = {idx:label for idx, label in enumerate(labels)}
print(f"id2label: {type(id2label)} {len(id2label)}\n{id2label}")

label2id = {label:idx for idx, label in enumerate(labels)}
print(f"label2id: {type(label2id)} {len(label2id)}\n{label2id}")

labels: <class 'list'> 6
['135', '136', '137', '138', '139', '390']
id2label: <class 'dict'> 6
{0: '135', 1: '136', 2: '137', 3: '138', 4: '139', 5: '390'}
label2id: <class 'dict'> 6
{'135': 0, '136': 1, '137': 2, '138': 3, '139': 4, '390': 5}


The dataset consists of texts, labeled with one or more skills.

Let's create a list that contains the labels, as well as 2 dictionaries that map labels to integers and back.

In [ ]:
# Upload the label list as a JSON file to the HF repo_id_dataset

labels_path = "labels.json"
with open(labels_path, 'w') as f:
    json.dump(labels, f)
print(f"labels saved to {labels_path}")

upload_file(
    path_or_fileobj = labels_path,
    path_in_repo    = labels_path,
    repo_id         = HF_name,
    repo_type       = "dataset"
    )
print(f"labels uploaded to https://huggingface.co/datasets/{HF_name}/tree/main/{labels_path}")

labels saved to labels.json


No files have been modified since last commit. Skipping to prevent empty commit.


labels uploaded to https://huggingface.co/datasets/claudelepere/skill_classification/tree/main/labels.json


## Preprocess data

As models like BERT don't expect text as direct input, but rather **`input_ids`**, etc., we tokenize the text using the tokenizer. Here I'm using the `AutoTokenizer` API, which will automatically load the appropriate tokenizer based on the checkpoint on the hub.

What's a bit tricky is that we also need to provide labels to the model. For multi-label text classification, this is a **matrix of shape (batch_size, num_labels)**. Also important: this should be a tensor of floats rather than integers, otherwise PyTorch' **BCEWithLogitsLoss** (which the model will use) will complain, as explained [here](https://discuss.pytorch.org/t/multi-label-binary-classification-result-type-float-cant-be-cast-to-the-desired-output-type-long/117915/3).

### Preprocess (examples, not example, because batched=True => examples is a batch)

In [ ]:
# Tokenize 'text' in the 3 datasets, train, validation and test

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [ ]:
def preprocess_data(examples, indices):
  text = examples['text']    # Batch of texts

  encoding = tokenizer(
      text,                             # Tokenize text
      truncation     = True,
      padding        = 'max_length',
      max_length     = 512,
      return_tensors = 'pt'             # Return PyTorch tensors
      )

  # Create an empty label matrix
  labels_matrix = torch.zeros((len(text), len(labels)), dtype=torch.float32)
  #print(f"labels_matrix: {type(labels_matrix)} {labels_matrix.shape}")

  # Populate label matrix
  for idx, label in enumerate(labels):
    #print(f"idx:{idx} label:{label}")
    if label in examples:
      labels_matrix[:, idx] = torch.tensor(
          [1.0 if val else 0.0 for val in examples[label]],
          dtype=torch.float32
          )
  #print(f"labels_matrix: {type(labels_matrix)} {labels_matrix.shape}")

  # Add labels to the encoding
  encoding['labels'] = labels_matrix
  #print(f"encoding['labels']: {encoding['labels']}")

  return encoding

In [ ]:
# Create the 3 encoded datasets, train, validation and test

encoded_dataset = dataset.map(
    preprocess_data,
    batched        = True,
    remove_columns = dataset['train'].column_names,
    with_indices   = True
    )
train_dataset      = encoded_dataset['train']
validation_dataset = encoded_dataset['validation']
test_dataset       = encoded_dataset['test']
print(f"encoded_dataset: {type(encoded_dataset)} {encoded_dataset.shape}\n{encoded_dataset}")
print(f"train_dataset: {type(train_dataset)} {train_dataset.shape}\n{train_dataset}")
print(f"validation_dataset: {type(validation_dataset)} {validation_dataset.shape}\n{validation_dataset}")
print(f"test_dataset: {type(test_dataset)} {test_dataset.shape}\n{test_dataset}")

Map:   0%|          | 0/800 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/150 [00:00<?, ? examples/s]

encoded_dataset: <class 'datasets.dataset_dict.DatasetDict'> {'train': (800, 4), 'validation': (50, 4), 'test': (150, 4)}
DatasetDict({
    train: Dataset({
        features: ['input_ids', 'token_type_ids', 'attention_mask', 'labels'],
        num_rows: 800
    })
    validation: Dataset({
        features: ['input_ids', 'token_type_ids', 'attention_mask', 'labels'],
        num_rows: 50
    })
    test: Dataset({
        features: ['input_ids', 'token_type_ids', 'attention_mask', 'labels'],
        num_rows: 150
    })
})
train_dataset: <class 'datasets.arrow_dataset.Dataset'> (800, 4)
Dataset({
    features: ['input_ids', 'token_type_ids', 'attention_mask', 'labels'],
    num_rows: 800
})
validation_dataset: <class 'datasets.arrow_dataset.Dataset'> (50, 4)
Dataset({
    features: ['input_ids', 'token_type_ids', 'attention_mask', 'labels'],
    num_rows: 50
})
test_dataset: <class 'datasets.arrow_dataset.Dataset'> (150, 4)
Dataset({
    features: ['input_ids', 'token_type_ids', 'atten

In [ ]:
example = encoded_dataset['train'][0]
print(f"example: {type(example)} {example.keys()}\n{example}")

print()

print(f"example['input_ids']: {type(example['input_ids'])} {len(example['input_ids'])}\n{example['input_ids']}")
print(f"example['token_type_ids']: {type(example['token_type_ids'])} {len(example['token_type_ids'])}\n{example['token_type_ids']}")
print(f"example['attention_mask']: {type(example['attention_mask'])} {len(example['attention_mask'])}\n{example['attention_mask']}")
print(f"example['labels']:  {type(example['labels'])} {len(example['labels'])}\n{example['labels']}")

example: <class 'dict'> dict_keys(['input_ids', 'token_type_ids', 'attention_mask', 'labels'])
{'input_ids': [101, 6925, 22750, 10552, 1011, 2326, 6959, 10669, 2373, 12170, 1010, 10147, 2527, 1010, 5796, 19342, 6925, 22750, 10552, 6925, 22750, 10552, 2003, 2747, 2559, 2005, 1037, 2326, 6959, 10669, 2005, 2028, 1997, 2256, 8228, 7846, 2241, 1999, 9371, 1012, 2707, 3058, 1024, 5890, 1013, 5718, 1013, 2484, 9367, 1024, 3054, 2000, 2146, 2744, 8775, 19453, 2075, 1024, 8893, 3260, 8080, 1998, 3189, 2836, 1997, 2490, 5826, 1998, 16599, 8377, 1998, 7300, 2000, 10444, 2448, 18079, 8189, 5897, 1998, 7316, 6295, 6133, 3679, 9686, 25015, 3508, 2007, 17088, 4287, 2041, 3361, 8518, 1999, 3001, 5918, 5065, 2030, 5972, 3014, 2030, 5662, 2011, 3325, 2012, 2560, 1015, 2095, 1997, 3325, 1999, 1037, 2714, 2597, 1006, 2326, 6959, 1007, 3716, 1997, 2551, 2007, 2009, 2490, 5826, 1013, 6194, 3716, 1997, 5796, 19342, 5097, 1010, 2373, 12170, 1998, 10147, 2527, 19376, 1999, 2394, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [ ]:
tokenizer.decode(example['input_ids'])

'[CLS] talencia consulting - service delivery coordinator power bi, jira, ms 365 talencia consulting talencia consulting is currently looking for a service delivery coordinator for one of our renowned clients based in brussels. start date : 01 / 07 / 24 duration : mid to long term assignment homeworking : hybrid mission monitor and report performance of support partners and propose improvements and solutions to incidents run govenance and reporting meetings manage daily escalation with vendors carry out financial tasks in systems requirements bachelor or masters degree or equivalent by experience at least 1 year of experience in a similar position ( service delivery ) knowledge of working with it support partners / processes knowledge of ms 365 applications, power bi and jira fluent in english [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PA

In [ ]:
[id2label[idx] for idx, label in enumerate(example['labels']) if label == 1.0]

['136', '137', '138']

Finally, we set the format of our data to PyTorch tensors. This will turn the training, validation and test sets into standard PyTorch [datasets](https://pytorch.org/docs/stable/data.html).

In [ ]:
# Set PyTorch format to ensures correctness and compatibility with PyTorch pipelines

# The 3 Hugging Face Dataset are formatted as PyTorch Dataset
encoded_dataset.set_format('torch')

## Define model

Here we define a **model that includes a pre-trained base (i.e. the weights from bert-base-uncased) are loaded, with a random initialized classification head (linear layer) on top**. One should fine-tune this head, together with the pre-trained base on a labeled dataset.

This is also printed by the warning.

We set the `problem_type` to be "multi_label_classification", as this will make sure the appropriate loss function is used (namely [**BCEWithLogitsLoss**](https://pytorch.org/docs/stable/generated/torch.nn.BCEWithLogitsLoss.html)). We also make sure the output layer has `len(labels)` output neurons, and we set the id2label and label2id mappings.

In [ ]:
# Define the model

model = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-uncased",
    problem_type="multi_label_classification",
    num_labels=len(labels),
    id2label=id2label,
    label2id=label2id
    )

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


## Train the model!

We are going to train the model using HuggingFace's Trainer API. This requires us to define 2 things:

* `TrainingArguments`, which specify training hyperparameters. All options can be found in the [docs](https://huggingface.co/transformers/main_classes/trainer.html#trainingarguments). Below, we for example specify that we want to evaluate after every epoch of training, we would like to save the model every epoch, we set the learning rate, the batch size to use for training/evaluation, how many epochs to train for, and so on.
* a `Trainer` object (docs can be found [here](https://huggingface.co/transformers/main_classes/trainer.html#id1)).

In [ ]:
batch_size  = 8     # 8, 16, 32, 64, 128
metric_name = "f1"

### TrainingArguments

In [ ]:
output_dir = "training_results"  # where model predictions and checkpoints will be written during training
args = TrainingArguments(
    output_dir                  = output_dir,
    overwrite_output_dir        = True,
    logging_dir                 = "logs",
    logging_steps               = 50,
    save_steps                  = 500,
    save_total_limit            = 2,
    eval_strategy               = "epoch",
    save_strategy               = "epoch",
    learning_rate               = 2e-5,
    per_device_train_batch_size = batch_size,
    per_device_eval_batch_size  = batch_size,
    num_train_epochs            = 5,
    weight_decay                = 0.01,
    load_best_model_at_end      = True,
    metric_for_best_model       = metric_name,
    #push_to_hub                 = True,             # push the model to the HF Hub
    run_name                   = "BERT-multilabel-lr2e5-epochs5-dataset_11_50000",
    report_to                  = "none" #"wandb"
    )

We are also going to compute metrics while training. For this, we need to define a `compute_metrics` function, that returns a dictionary with the desired metric values.

In [ ]:
# Metrics
#   source: https://jesusleal.io/2021/04/21/Longformer-multilabel-classification/

def multi_label_metrics(predictions, labels, threshold=0.2):
    _average = 'micro'    # 'micro' or 'weighted'

    # first, apply sigmoid on predictions which are of shape (batch_size, num_labels)
    sigmoid = torch.nn.Sigmoid()
    probs   = sigmoid(torch.Tensor(predictions))

    # next, use threshold to turn them into integer predictions
    y_pred = np.zeros(probs.shape)
    y_pred[np.where(probs >= threshold)] = 1

    # finally, compute metrics
    y_true               = labels
    f1                   = f1_score               (y_true=y_true, y_pred=y_pred, average=_average)    #, zero_division=1)
    precision            = precision_score        (y_true=y_true, y_pred=y_pred, average=_average)    #, zero_division=1)
    recall               = recall_score           (y_true=y_true, y_pred=y_pred, average=_average)    #, zero_division=1)
    roc_auc              = roc_auc_score          (y_true=y_true, y_score=probs, average=_average)
    precision_recall_auc = average_precision_score(y_true=y_true, y_score=probs, average=_average)
    accuracy             = accuracy_score         (y_true=y_true, y_pred=y_pred)

    # return as dictionary
    metrics = {
        'f1'                  : f1,
        'precision'           : precision,
        'recall'              : recall,
        'roc_auc'             : roc_auc,
        'precision_recall_auc': precision_recall_auc,
        'accuracy'            : accuracy
        }

    return metrics

In [ ]:
def compute_metrics(p: EvalPrediction):
    preds = p.predictions[0] if isinstance(p.predictions, tuple) else p.predictions
    result = multi_label_metrics(
        predictions = preds,
        labels      = p.label_ids
        )
    return result

Let's verify a batch as well as a forward pass:

In [ ]:
print(f"inputids:        {type(encoded_dataset['train']['input_ids'][0])}\t{encoded_dataset['train']['input_ids'][0].shape}")
print(f"token_type_ids': {type(encoded_dataset['train']['token_type_ids'][0])}\t{encoded_dataset['train']['token_type_ids'][0].shape}")
print(f"attention_mask:  {type(encoded_dataset['train']['attention_mask'][0])}\t{encoded_dataset['train']['attention_mask'][0].shape}")
print(f"labels:          {type(encoded_dataset['train'][0]['labels'])}\t{encoded_dataset['train'][0]['labels'].shape}")

inputids:        <class 'torch.Tensor'>	torch.Size([512])
token_type_ids': <class 'torch.Tensor'>	torch.Size([512])
attention_mask:  <class 'torch.Tensor'>	torch.Size([512])
labels:          <class 'torch.Tensor'>	torch.Size([6])


In [ ]:
# Execute the forward pass

outputs = model(
    input_ids      = encoded_dataset['train']['input_ids'][0].unsqueeze(0),
    attention_mask = encoded_dataset['train']['attention_mask'][0].unsqueeze(0),
    labels         = encoded_dataset['train'][0]['labels'].unsqueeze(0)
    )

print(f"outputs: {type(outputs)} {outputs.keys()}\n{outputs}")

outputs: <class 'transformers.modeling_outputs.SequenceClassifierOutput'> odict_keys(['loss', 'logits'])
SequenceClassifierOutput(loss=tensor(0.6138, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>), logits=tensor([[-0.0152,  0.5826,  0.1590, -0.1949, -0.4276, -0.1111]],
       grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)


Let's start training!

In [ ]:
## Create the trainer

trainer = Trainer(
    model,
    args,
    train_dataset=encoded_dataset["train"],
    eval_dataset=encoded_dataset["validation"],
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
    )


<ipython-input-26-485be3f189a5>:3: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(


In [ ]:
# Train, save the results as a JSON file

train_output  = trainer.train()

train_results = {
    'global_step':   train_output.global_step,    # total steps completed during training
    'training_loss': train_output.training_loss,  # average loss during training
    'metrics':       train_output.metrics         # dictionary of metrics
}

with open("train_results.json", "w") as f:
  json.dump(train_results, f, indent=4)

In [ ]:
print("Training successfully completed.")

Training successfully completed.


## Evaluate

After training, we evaluate our model on the validation set.

In [ ]:
# Evaluate, save the output as a JSON file

eval_output = trainer.evaluate()

with open("eval_results.json", "w") as f:
  json.dump(eval_output, f, indent=4)

In [ ]:
print("Evaluation successfully completed.")

Evaluation successfully completed.


In [ ]:
# Save the model

model_path = "model"
trainer.save_model(model_path)

In [ ]:
# Upload the model and the tokenizer to the HF repo_id_model

model     = AutoModelForSequenceClassification.from_pretrained(model_path)
tokenizer = AutoTokenizer.from_pretrained(model_path)

model.push_to_hub(repo_id_model)
tokenizer.push_to_hub(repo_id_model)

README.md:   0%|          | 0.00/5.17k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

No files have been modified since last commit. Skipping to prevent empty commit.


CommitInfo(commit_url='https://huggingface.co/claudelepere/skill_classification/commit/0ea614788d0dd3b5b91b0e598588e8780229f5bd', commit_message='Upload tokenizer', commit_description='', oid='0ea614788d0dd3b5b91b0e598588e8780229f5bd', pr_url=None, repo_url=RepoUrl('https://huggingface.co/claudelepere/skill_classification', endpoint='https://huggingface.co', repo_type='model', repo_id='claudelepere/skill_classification'), pr_revision=None, pr_num=None)

In [ ]:
# Upload train_results.json and eval_results.json to the HF repo_id_dataset
#   BETTER to upload to wanddb repo?

upload_file(
    path_or_fileobj = "train_results.json",
    path_in_repo    = "train_results.json",
    repo_id         = HF_name,
    repo_type       = "dataset"
    )

upload_file(
    path_or_fileobj = "eval_results.json",
    path_in_repo    = "eval_results.json",
    repo_id         = HF_name,
    repo_type       = "dataset"
    )

CommitInfo(commit_url='https://huggingface.co/datasets/claudelepere/skill_classification/commit/4a46eb4f4887902d7bcb15ef90a31e66f526a9e7', commit_message='Upload eval_results.json with huggingface_hub', commit_description='', oid='4a46eb4f4887902d7bcb15ef90a31e66f526a9e7', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/claudelepere/skill_classification', endpoint='https://huggingface.co', repo_type='dataset', repo_id='claudelepere/skill_classification'), pr_revision=None, pr_num=None)

## Predict results on the test dataset
Faire la même chose pour l'évaluation?

In [ ]:
# Set the model to evaluation mode to disable dropout and other training-specific behaviors

model.eval()

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e

In [ ]:
# Predict results on the test dataset

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

all_preds       = []
all_probs       = []
all_true_labels = []
threshold       = 0.5

for batch in tqdm(test_loader):
  batch = {k: v.to(device) for k, v in batch.items()}
  with torch.no_grad():
    outputs = model(**batch)
  logits = outputs.logits

  # Convert logits to probabilities and probabilities to predictions
  sigmoid = torch.nn.Sigmoid()
  probs   = sigmoid(logits).cpu().numpy()    # Convert to Numpy
  preds   = (probs > threshold).astype(int)  # Convert to binary Numpy array

  # Accumulate probabilities, predictions and labels
  all_probs.append(probs)
  all_preds.append(preds)
  all_true_labels.append(batch['labels'].cpu().numpy())

# Concatenate results from all batches
all_probs       = np.concatenate(all_probs, axis=0)        # shape: [num_samples, num_labels]
all_preds       = np.concatenate(all_preds, axis=0)        # shape: [num_samples, num_labels]
all_true_labels = np.concatenate(all_true_labels, axis=0)  # shape: [num_samples, num_labels]

#np.set_printoptions(threshold=np.inf)
print(f"all_probs:       {type(all_probs)} {all_probs.shape} {all_probs}")
print(f"all_preds:       {type(all_preds)} {all_preds.shape} {all_preds}")
print(f"all_true_labels: {type(all_true_labels)} {all_true_labels.shape} {all_true_labels}")

# Classification report for precision, recall, F1 score
print(classification_report(
    y_true=all_true_labels,
    y_pred=all_preds,
    target_names=labels,
    zero_division=0
    ))

# ROC AUC for multi-label classification
roc_auc = roc_auc_score(
    y_true=all_true_labels,
    y_score=all_probs,
    average='micro'
    )
print(f"ROC AUC: {roc_auc}")

  0%|          | 0/19 [00:00<?, ?it/s]

all_probs:       <class 'numpy.ndarray'> (150, 6) [[0.02094165 0.04409546 0.4189186  0.9326476  0.87955445 0.02691205]
 [0.01527706 0.07909876 0.72141826 0.936262   0.7933707  0.01909798]
 [0.02059294 0.04595084 0.55793524 0.93861586 0.8135784  0.02052253]
 [0.02282132 0.04522771 0.3917761  0.9233704  0.87874794 0.02560659]
 [0.01882656 0.0576524  0.69199663 0.944607   0.75039846 0.01739042]
 [0.02074783 0.04538324 0.45891106 0.9360555  0.8758924  0.02739669]
 [0.02525343 0.04481065 0.3535169  0.9266259  0.88390875 0.03283959]
 [0.0189189  0.04986935 0.46103737 0.9221578  0.8530785  0.02024274]
 [0.01836344 0.04766958 0.51598734 0.9425803  0.8517098  0.02201167]
 [0.02411748 0.1281895  0.8318715  0.9278949  0.58839476 0.02619971]
 [0.02616293 0.04890998 0.36429513 0.91182595 0.88642806 0.03102494]
 [0.01971913 0.04647465 0.5809833  0.95188916 0.8231941  0.0204608 ]
 [0.01607305 0.07461844 0.65596294 0.93190455 0.803178   0.02036708]
 [0.02531499 0.08523843 0.6950935  0.90919304 0.67623

In [ ]:
print("Predictions 1 successfully completed.")

Predictions 1 successfully completed.


### Or otherwise

In [ ]:
predictions = trainer.predict(test_dataset)
print(predictions.predictions)  # Model logits
print(predictions.label_ids)    # Ground truth labels
print(predictions.metrics)      # Metrics

[[-3.844851   -3.076301   -0.32721427  2.6280885   1.9882174  -3.5879004 ]
 [-4.166008   -2.4546556   0.9515076   2.6871152   1.3453646  -3.9388897 ]
 [-3.861999   -3.033143    0.23278645  2.7272544   1.473432   -3.865496  ]
 [-3.7569742  -3.049763   -0.4398526   2.4890478   1.9806266  -3.6389654 ]
 [-3.9534807  -2.7939422   0.8094705   2.836315    1.1007385  -4.0342927 ]
 [-3.8543475  -3.0461671  -0.16472714  2.683659    1.9540944  -3.569554  ]
 [-3.6532156  -3.0594637  -0.6036158   2.5359783   2.029977   -3.3827298 ]
 [-3.9484937  -2.947193   -0.1561671   2.4720335   1.7589526  -3.8795087 ]
 [-3.9788592  -2.9946187   0.06397098  2.7982323   1.7480744  -3.7939248 ]
 [-3.7004051  -1.9170624   1.5989492   2.5547938   0.35733324 -3.615458  ]
 [-3.6169004  -2.9676273  -0.55677015  2.3361359   2.0547633  -3.4414473 ]
 [-3.90625    -3.021259    0.3268112   2.9849422   1.5381395  -3.8685713 ]
 [-4.1144075  -2.5178185   0.6453551   2.61632     1.4062765  -3.873258  ]
 [-3.6507177  -2.3732111 

In [ ]:
print("Predictions 2 successfully completed.")